server:
  port: 9090

spring:
  application:
    name: send-email-service
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhurgrishahjahan28@gmail.com
    password: etuffvpoidcaxqdq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
